development:
  adapter: postgresql
  encoding: utf8
  database: shopper_challenge_mzellhuber_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: shopper_challenge_mzellhuber_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: shopper_challenge_mzellhuber_production
  pool: 5
  username: 
  password: